# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gRPC.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gRPC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngRPC.proto\"*\n\x12IniciarJogoRequest\x12\x14\n\x0cnome_cliente\x18\x01 \x01(\t\"[\n\x10IniciarJogoReply\x12\x12\n\ncliente_id\x18\x01 \x01(\t\x12\x19\n\x11palavra_escondida\x18\x02 \x01(\t\x12\x18\n\x10\x63hutes_restantes\x18\x03 \x01(\x05\"5\n\x0ePalpiteRequest\x12\x12\n\ncliente_id\x18\x01 \x01(\t\x12\x0f\n\x07palpite\x18\x02 \x01(\t\"J\n\rResultadoJogo\x12\x14\n\x0cnome_cliente\x18\x01 \x01(\t\x12\x0f\n\x07palavra\x18\x02 \x01(\t\x12\x12\n\nisVencedor\x18\x03 \x01(\x08\"\x17\n\x15GetLeaderboardRequest\":\n\x13GetLeaderboardReply\x12#\n\x0bleaderboard\x18\x01 \x03(\x0b\x32\x0e.ResultadoJogo\"\xcf\x01\n\x0fStatusJogoReply\x12*\n\x06\x65stado\x18\x01 \x01(\x0e\x32\x1a.StatusJogoReply.GameState\x12\x19\n\x11palavra_escondida\x18\x02 \x01(\t\x12\x18\n\x10\x63hutes_restantes\x18\x03 \x01(\x05\x12\x17\n\x0fletras_chutadas\x18\x04 \x01(\t\x12\x10\n\x08messagem\x18\x05 \x01(\t\"0\n\tGameState\x12\x0b\n\x07JOGANDO\x10\x00\x12\n\n\x06GANHOU\x10\x01\x12\n\n\x06PERDEU\x10\x02\x32\xb8\x01\n\x0c\x46orcaService\x12\x35\n\x0bIniciarJogo\x12\x13.IniciarJogoRequest\x1a\x11.IniciarJogoReply\x12\x31\n\x0c\x46\x61zerPalpite\x12\x0f.PalpiteRequest\x1a\x10.StatusJogoReply\x12>\n\x0eGetLeaderboard\x12\x16.GetLeaderboardRequest\x1a\x14.GetLeaderboardReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INICIARJOGOREQUEST']._serialized_start=14
  _globals['_INICIARJOGOREQUEST']._serialized_end=56
  _globals['_INICIARJOGOREPLY']._serialized_start=58
  _globals['_INICIARJOGOREPLY']._serialized_end=149
  _globals['_PALPITEREQUEST']._serialized_start=151
  _globals['_PALPITEREQUEST']._serialized_end=204
  _globals['_RESULTADOJOGO']._serialized_start=206
  _globals['_RESULTADOJOGO']._serialized_end=280
  _globals['_GETLEADERBOARDREQUEST']._serialized_start=282
  _globals['_GETLEADERBOARDREQUEST']._serialized_end=305
  _globals['_GETLEADERBOARDREPLY']._serialized_start=307
  _globals['_GETLEADERBOARDREPLY']._serialized_end=365
  _globals['_STATUSJOGOREPLY']._serialized_start=368
  _globals['_STATUSJOGOREPLY']._serialized_end=575
  _globals['_STATUSJOGOREPLY_GAMESTATE']._serialized_start=527
  _globals['_STATUSJOGOREPLY_GAMESTATE']._serialized_end=575
  _globals['_FORCASERVICE']._serialized_start=578
  _globals['_FORCASERVICE']._serialized_end=762
# @@protoc_insertion_point(module_scope)
