# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gRPC_pb2 as gRPC__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gRPC_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForcaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IniciarJogo = channel.unary_unary(
                '/ForcaService/IniciarJogo',
                request_serializer=gRPC__pb2.IniciarJogoRequest.SerializeToString,
                response_deserializer=gRPC__pb2.IniciarJogoReply.FromString,
                _registered_method=True)
        self.FazerPalpite = channel.unary_unary(
                '/ForcaService/FazerPalpite',
                request_serializer=gRPC__pb2.PalpiteRequest.SerializeToString,
                response_deserializer=gRPC__pb2.StatusJogoReply.FromString,
                _registered_method=True)
        self.GetLeaderboard = channel.unary_unary(
                '/ForcaService/GetLeaderboard',
                request_serializer=gRPC__pb2.GetLeaderboardRequest.SerializeToString,
                response_deserializer=gRPC__pb2.GetLeaderboardReply.FromString,
                _registered_method=True)


class ForcaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IniciarJogo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FazerPalpite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeaderboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForcaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IniciarJogo': grpc.unary_unary_rpc_method_handler(
                    servicer.IniciarJogo,
                    request_deserializer=gRPC__pb2.IniciarJogoRequest.FromString,
                    response_serializer=gRPC__pb2.IniciarJogoReply.SerializeToString,
            ),
            'FazerPalpite': grpc.unary_unary_rpc_method_handler(
                    servicer.FazerPalpite,
                    request_deserializer=gRPC__pb2.PalpiteRequest.FromString,
                    response_serializer=gRPC__pb2.StatusJogoReply.SerializeToString,
            ),
            'GetLeaderboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeaderboard,
                    request_deserializer=gRPC__pb2.GetLeaderboardRequest.FromString,
                    response_serializer=gRPC__pb2.GetLeaderboardReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ForcaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ForcaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForcaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IniciarJogo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ForcaService/IniciarJogo',
            gRPC__pb2.IniciarJogoRequest.SerializeToString,
            gRPC__pb2.IniciarJogoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FazerPalpite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ForcaService/FazerPalpite',
            gRPC__pb2.PalpiteRequest.SerializeToString,
            gRPC__pb2.StatusJogoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeaderboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ForcaService/GetLeaderboard',
            gRPC__pb2.GetLeaderboardRequest.SerializeToString,
            gRPC__pb2.GetLeaderboardReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
