# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import blackjack_pb2 as blackjack__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in blackjack_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlackjackStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGame = channel.unary_unary(
                '/blackjack.Blackjack/StartGame',
                request_serializer=blackjack__pb2.GameRequest.SerializeToString,
                response_deserializer=blackjack__pb2.GameResponse.FromString,
                _registered_method=True)
        self.Hit = channel.unary_unary(
                '/blackjack.Blackjack/Hit',
                request_serializer=blackjack__pb2.GameRequest.SerializeToString,
                response_deserializer=blackjack__pb2.GameResponse.FromString,
                _registered_method=True)
        self.Stand = channel.unary_unary(
                '/blackjack.Blackjack/Stand',
                request_serializer=blackjack__pb2.GameRequest.SerializeToString,
                response_deserializer=blackjack__pb2.GameResponse.FromString,
                _registered_method=True)


class BlackjackServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Hit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlackjackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=blackjack__pb2.GameRequest.FromString,
                    response_serializer=blackjack__pb2.GameResponse.SerializeToString,
            ),
            'Hit': grpc.unary_unary_rpc_method_handler(
                    servicer.Hit,
                    request_deserializer=blackjack__pb2.GameRequest.FromString,
                    response_serializer=blackjack__pb2.GameResponse.SerializeToString,
            ),
            'Stand': grpc.unary_unary_rpc_method_handler(
                    servicer.Stand,
                    request_deserializer=blackjack__pb2.GameRequest.FromString,
                    response_serializer=blackjack__pb2.GameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blackjack.Blackjack', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blackjack.Blackjack', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Blackjack(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackjack.Blackjack/StartGame',
            blackjack__pb2.GameRequest.SerializeToString,
            blackjack__pb2.GameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Hit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackjack.Blackjack/Hit',
            blackjack__pb2.GameRequest.SerializeToString,
            blackjack__pb2.GameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blackjack.Blackjack/Stand',
            blackjack__pb2.GameRequest.SerializeToString,
            blackjack__pb2.GameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
