# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blackjack.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'blackjack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62lackjack.proto\x12\tblackjack\"#\n\x04\x43\x61rd\x12\x0c\n\x04suit\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"&\n\x04Hand\x12\x1e\n\x05\x63\x61rds\x18\x01 \x03(\x0b\x32\x0f.blackjack.Card\"\"\n\x0bGameRequest\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\"\xaa\x01\n\x0cGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12$\n\x0bplayer_hand\x18\x02 \x01(\x0b\x32\x0f.blackjack.Hand\x12$\n\x0b\x64\x65\x61ler_hand\x18\x03 \x01(\x0b\x32\x0f.blackjack.Hand\x12\x14\n\x0cplayer_score\x18\x04 \x01(\x05\x12\x14\n\x0c\x64\x65\x61ler_score\x18\x05 \x01(\x05\x12\x11\n\tgame_over\x18\x06 \x01(\x08\x32\xbb\x01\n\tBlackjack\x12<\n\tStartGame\x12\x16.blackjack.GameRequest\x1a\x17.blackjack.GameResponse\x12\x36\n\x03Hit\x12\x16.blackjack.GameRequest\x1a\x17.blackjack.GameResponse\x12\x38\n\x05Stand\x12\x16.blackjack.GameRequest\x1a\x17.blackjack.GameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blackjack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARD']._serialized_start=30
  _globals['_CARD']._serialized_end=65
  _globals['_HAND']._serialized_start=67
  _globals['_HAND']._serialized_end=105
  _globals['_GAMEREQUEST']._serialized_start=107
  _globals['_GAMEREQUEST']._serialized_end=141
  _globals['_GAMERESPONSE']._serialized_start=144
  _globals['_GAMERESPONSE']._serialized_end=314
  _globals['_BLACKJACK']._serialized_start=317
  _globals['_BLACKJACK']._serialized_end=504
# @@protoc_insertion_point(module_scope)
